import {
  MdNotifications,
  MdHelpCenter,
  MdVerified,
  MdTimer,
  MdCloudUpload,
  MdOutlineReportProblem,
} from "react-icons/md";
import {FiCopy} from 'react-icons/fi'
import {
  AiFillFire,
  AiFillHeart,
  AiOutlineHeart,
  AiFillCloseCircle,
} from "react-icons/ai";
import {
  BsSearch,
  BsCircleFill,
  BsImage,
  BsImages,
  BsFillAlarmFill,
  BsFillCalendarDateFill,
  BsCalendar3,
  BsThreeDots,
} from "react-icons/bs";
import { CgMenuLeft, CgMenuRight } from "react-icons/cg";
import { DiJqueryLogo } from "react-icons/di";
import {
  FaUserAlt,
  FaRegImage,
  FaUserEdit,
  FaFilter,
  FaAngleDown,
  FaAngleUp,
  FaWallet,
  FaMusic,
  FaVideo,
  FaImages,
} from "react-icons/fa";
import {
  TbDownloadOff,
  TbDownload,
  TbArrowBigLeftLines,
  TbArrowBigRightLines,
} from "react-icons/tb";
import { GrClose } from "react-icons/gr";
import { RiSendPlaneFill } from "react-icons/ri";
import {
  TiSocialFacebook,
  TiSocialLinkedin,
  TiSocialTwitter,
  TiSocialInstagram,
  TiSocialYoutube,
  TiArrrownSortedDown,
  TiArrrownSortedUp,
  TiArrowLeftThick,
  TiArrowRightThick,
  TiTick,
} from "react-icons/ti";

export {
  MdNotifications,
  MdOutlineReportProblem,
  DiJqueryLogo,
  BsSearch,
  BsCircleFill,
  CgMenuLeft,
  CgMenuRight,
  FaUserAlt,
  FaUserEdit,
  FaRegImage,
  MdHelpCenter,
  TbDownloadOff,
  TbDownload,
  TiSocialFacebook,
  TiSocialLinkedin,
  TiSocialTwitter,
  TiSocialInstagram,
  TiSocialYoutube,
  TiArrrownSortedDown,
  TiArrrownSortedUp,
  TiArrowLeftThick,
  TiArrowRightThick,
  GrClose,
  RiSendPlaneFill,
  MdVerified,
  MdTimer,
  MdCloudUpload,
  AiFillFire,
  AiFillHeart,
  AiOutlineHeart,
  AiFillCloseCircle,
  TbArrowBigLeftLines,
  TbArrowBigRightLines,
  FaFilter,
  FaAngleDown,
  FaAngleUp,
  FaWallet,
  FaMusic,
  FaVideo,
  FaImages,
  TiTick,
  BsImage,
  BsImages,
  BsFillAlarmFill,
  BsFillCalendarDateFill,
  BsCalendar3,
  BsThreeDots,
  FiCopy,
};
